version: '3'
services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - 80:80
    links:
      - rss-ui
      - rss-api
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
  rss-ui:
    build:
      context: .
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./node_modules:/usr/src/app/node_modules
  rss-api:
    build: ./api
    environment:
      CONTEXT_PATH: /api
    volumes:
      - ../change-api/swagger.yml:/usr/src/app/swagger.yml
